"""Add transport_type to Transaction model

Revision ID: 435b155b228e
Revises: 
Create Date: 2025-05-12 09:08:25.296680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '435b155b228e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transport_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('transport_type')

    # ### end Alembic commands ###
